### ISSUE TITLE
flask create-db fails to CREATE TABLE bulletin

### ISSUE THREAD

**Issue by saadcaffeine** [sjacorg/bayanat#13]
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "("
LINE 28:  search TEXT GENERATED ALWAYS AS (
                                          ^

[SQL: 
CREATE TABLE bulletin (
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted BOOLEAN, 
	id SERIAL NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	title_ar VARCHAR(255), 
	sjac_title VARCHAR(255), 
	sjac_title_ar VARCHAR(255), 
	user_id INTEGER, 
	assigned_to_id INTEGER, 
	description TEXT, 
	reliability_score INTEGER, 
	first_peer_reviewer_id INTEGER, 
	second_peer_reviewer_id INTEGER, 
	publish_date TIMESTAMP WITHOUT TIME ZONE, 
	documentation_date TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(255), 
	source_link VARCHAR(255), 
	source_link_type BOOLEAN, 
	ref VARCHAR[], 
	originid VARCHAR, 
	comments TEXT, 
	review TEXT, 
	review_action VARCHAR, 
	tsv TSVECTOR, 
	search TEXT GENERATED ALWAYS AS (
        (((((((((((((((((id)::text || ' '::text) || (COALESCE(title, ''::character varying))::text) || ' '::text) ||
                        (COALESCE(title_ar, ''::character varying))::text) || ' '::text) ||
                      COALESCE(description, ''::text)) || ' '::text) ||
                    (COALESCE(originid, ''::character varying))::text) || ' '::text) ||
                  (COALESCE(sjac_title, ''::character varying))::text) || ' '::text) ||
                (COALESCE(sjac_title_ar, ''::character varying))::text) || ' '::text) ||
                (COALESCE(source_link, ''::character varying))::text) || ' '::text) 
                ||  ' '::text) || COALESCE(comments, ''::text)
        ) STORED, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "user" (id), 
	FOREIGN KEY(assigned_to_id) REFERENCES "user" (id), 
	FOREIGN KEY(first_peer_reviewer_id) REFERENCES "user" (id), 
	FOREIGN KEY(second_peer_reviewer_id) REFERENCES "user" (id)
)


```

**To Reproduce**

Follow Manual installation steps as at https://docs.bayanat.org/en/install
Configure following configuration steps as at https://docs.bayanat.org/en/config

```
(env) pi@raspberry:~/bayanat$ export FLASK_APP=run.py
(env) pi@raspberry:~/bayanat$ flask create-db
Trigram extension installed successfully
Postgis extension installed successfully
Traceback (most recent call last):
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 28:  search TEXT GENERATED ALWAYS AS (
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/bayanat/env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/bayanat/enferno/commands.py", line 23, in create_db
    db.create_all()
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4742, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2980, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 850, in visit_metadata
    _is_metadata_operation=True,
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1296, in _execute_ddl
    compiled,
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "("
LINE 28:  search TEXT GENERATED ALWAYS AS (
                                          ^

[SQL: 
CREATE TABLE bulletin (
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted BOOLEAN, 
	id SERIAL NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	title_ar VARCHAR(255), 
	sjac_title VARCHAR(255), 
	sjac_title_ar VARCHAR(255), 
	user_id INTEGER, 
	assigned_to_id INTEGER, 
	description TEXT, 
	reliability_score INTEGER, 
	first_peer_reviewer_id INTEGER, 
	second_peer_reviewer_id INTEGER, 
	publish_date TIMESTAMP WITHOUT TIME ZONE, 
	documentation_date TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(255), 
	source_link VARCHAR(255), 
	source_link_type BOOLEAN, 
	ref VARCHAR[], 
	originid VARCHAR, 
	comments TEXT, 
	review TEXT, 
	review_action VARCHAR, 
	tsv TSVECTOR, 
	search TEXT GENERATED ALWAYS AS (
        (((((((((((((((((id)::text || ' '::text) || (COALESCE(title, ''::character varying))::text) || ' '::text) ||
                        (COALESCE(title_ar, ''::character varying))::text) || ' '::text) ||
                      COALESCE(description, ''::text)) || ' '::text) ||
                    (COALESCE(originid, ''::character varying))::text) || ' '::text) ||
                  (COALESCE(sjac_title, ''::character varying))::text) || ' '::text) ||
                (COALESCE(sjac_title_ar, ''::character varying))::text) || ' '::text) ||
                (COALESCE(source_link, ''::character varying))::text) || ' '::text) 
                ||  ' '::text) || COALESCE(comments, ''::text)
        ) STORED, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "user" (id), 
	FOREIGN KEY(assigned_to_id) REFERENCES "user" (id), 
	FOREIGN KEY(first_peer_reviewer_id) REFERENCES "user" (id), 
	FOREIGN KEY(second_peer_reviewer_id) REFERENCES "user" (id)
)

]
(Background on this error at: http://sqlalche.me/e/14/f405)
(env) pi@raspberry:~/bayanat$ locate settings.py
/usr/lib/python3/dist-packages/isort/settings.py
/usr/lib/python3/dist-packages/jedi/settings.py
/usr/lib/python3/dist-packages/mypy/typeshed/third_party/2and3/pynamodb/settings.pyi
/usr/lib/python3/dist-packages/reportlab/rl_settings.py
/usr/share/doc/python3-guizero/examples/layout_settings.py
/usr/share/hplip/devicesettings.py
/usr/share/hplip/printsettings.py
/usr/share/system-config-printer/firewallsettings.py
/usr/share/system-config-printer/serversettings.py
(env) pi@raspberry:~/bayanat$ export FLASK_APP=run.py
(env) pi@raspberry:~/bayanat$ flask create-db
Trigram extension installed successfully
Postgis extension installed successfully
Traceback (most recent call last):
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 28:  search TEXT GENERATED ALWAYS AS (
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/bayanat/env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask/cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/bayanat/enferno/commands.py", line 23, in create_db
    db.create_all()
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4742, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2980, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 850, in visit_metadata
    _is_metadata_operation=True,
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1296, in _execute_ddl
    compiled,
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/bayanat/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "("
LINE 28:  search TEXT GENERATED ALWAYS AS (
                                          ^

[SQL: 
CREATE TABLE bulletin (
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted BOOLEAN, 
	id SERIAL NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	title_ar VARCHAR(255), 
	sjac_title VARCHAR(255), 
	sjac_title_ar VARCHAR(255), 
	user_id INTEGER, 
	assigned_to_id INTEGER, 
	description TEXT, 
	reliability_score INTEGER, 
	first_peer_reviewer_id INTEGER, 
	second_peer_reviewer_id INTEGER, 
	publish_date TIMESTAMP WITHOUT TIME ZONE, 
	documentation_date TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(255), 
	source_link VARCHAR(255), 
	source_link_type BOOLEAN, 
	ref VARCHAR[], 
	originid VARCHAR, 
	comments TEXT, 
	review TEXT, 
	review_action VARCHAR, 
	tsv TSVECTOR, 
	search TEXT GENERATED ALWAYS AS (
        (((((((((((((((((id)::text || ' '::text) || (COALESCE(title, ''::character varying))::text) || ' '::text) ||
                        (COALESCE(title_ar, ''::character varying))::text) || ' '::text) ||
                      COALESCE(description, ''::text)) || ' '::text) ||
                    (COALESCE(originid, ''::character varying))::text) || ' '::text) ||
                  (COALESCE(sjac_title, ''::character varying))::text) || ' '::text) ||
                (COALESCE(sjac_title_ar, ''::character varying))::text) || ' '::text) ||
                (COALESCE(source_link, ''::character varying))::text) || ' '::text) 
                ||  ' '::text) || COALESCE(comments, ''::text)
        ) STORED, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "user" (id), 
	FOREIGN KEY(assigned_to_id) REFERENCES "user" (id), 
	FOREIGN KEY(first_peer_reviewer_id) REFERENCES "user" (id), 
	FOREIGN KEY(second_peer_reviewer_id) REFERENCES "user" (id)
)

]
(Background on this error at: http://sqlalche.me/e/14/f405)```

**Comment by saadcaffeine** [comment]
Thank you for checking that, upgrading to PosgresSQL 14 resolves the issue. 

Debian Buster main apt sources.list provides Postgresql 11 as the most recent version. 
APT-Sources: http://cdn-aws.deb.debian.org/debian buster/main amd64 Packages

The PostgreSQL Global Development Group (PGDG) maintains an APT repository of PostgreSQL packages for Debian and Ubuntu located at http://apt.postgresql.org/pub/repos/apt/

to add apt.postgresql.org as a source for apt packages:

`sudo apt install postgresql-common gnupg
sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh`

to un install version 11 of PostgreSQL
`sudo apt remove postgresql-11`

and then install the latest version 
`sudo apt-get install postgresql`
